# Generated by Django 3.2.18 on 2023-04-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_room_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.FloatField(blank=True, max_length=200, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('paid_cust_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_cust_room_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_table',
            },
        ),
    ]
