# Generated by Django 3.2.18 on 2023-04-28 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer_id',
            new_name='paid_customer_id',
        ),
    ]
