# Generated by Django 3.2.18 on 2023-04-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_alter_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
