# Generated by Django 3.2.18 on 2023-04-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_auto_20230428_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
